Jkr/config
StyleCI/Docs pull request #14
Opened 2018-06-08 11:28 UTC by jackromo

Configuration fixes for docs. Added finder docs, moved docs for php-only and all-languages modes to separate files, and rewrote some bits and pieces for a better reading experience.

2018-06-08 11:34 UTC, jbrooksuk commented on all-languages.md
> +You may notice that the PHP and Javascript configurations look different. In fact, every languge has its own separate configuration options, with PHP retaining the PHP-only ones.
Typo in "language".

2018-06-08 11:34 UTC, jbrooksuk commented on all-languages.md
> +Each language's configuration must now fall under said language's name. For instance, observe the example config file below:
This is a bit of a mouthful, something like:

2018-06-08 11:35 UTC, jbrooksuk requested changes
A couple of changes.

2018-06-08 17:27 UTC, GrahamCampbell requested changes

2018-06-08 17:27 UTC, GrahamCampbell commented on all-languages.md
> +# All-Languages Mode
Would prefer multi vs all, since all implies everything is enabled. :)

2018-06-08 17:28 UTC, GrahamCampbell commented
Thanks Jack. Some feedback from James and I, then I'll merge.

2018-06-09 12:09 UTC, jackromo commented
I've now added a few fixes in the last commit. Let me know if there's anything else I missed.

2018-06-09 14:40 UTC, GrahamCampbell approved these changes

2018-06-09 14:41 UTC, merged